/**
 * @file d3d12_pipeline.c
 * @brief D3D12 pipeline state and shader management
 *
 * Handles root signatures, pipeline state objects, and shader compilation.
 * Shader bytecode is pre-compiled from shaders/triangle.hlsl using fxc.
 *
 * To recompile shaders:
 *   fxc /T vs_5_0 /E VSMain /Fh triangle_vs.h /Vn g_vs_bytecode triangle.hlsl
 *   fxc /T ps_5_0 /E PSMain /Fh triangle_ps.h /Vn g_ps_bytecode triangle.hlsl
 */

#include "d3d12_backend.h"

#ifdef BAV3D_PLATFORM_WINDOWS

    #include <stdio.h>

    /* Pre-compiled shader bytecode generated by fxc */
    #include "shaders/triangle_ps.h"
    #include "shaders/triangle_vs.h"

/* =============================================================================
 * Pipeline State
 * ============================================================================= */

b8 d3d12_create_triangle_pipeline(D3D12Backend* backend)
{
    HRESULT hr;

    /*
     * Root signature with one CBV for the MVP matrix.
     * Using a root descriptor (not a descriptor table) for simplicity.
     */
    D3D12_ROOT_PARAMETER root_param = {0};
    root_param.ParameterType = D3D12_ROOT_PARAMETER_TYPE_CBV;
    root_param.Descriptor.ShaderRegister = 0; /* b0 */
    root_param.Descriptor.RegisterSpace = 0;
    root_param.ShaderVisibility = D3D12_SHADER_VISIBILITY_VERTEX;

    D3D12_ROOT_SIGNATURE_DESC root_sig_desc = {0};
    root_sig_desc.NumParameters = 1;
    root_sig_desc.pParameters = &root_param;
    root_sig_desc.NumStaticSamplers = 0;
    root_sig_desc.pStaticSamplers = NULL;
    root_sig_desc.Flags = D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT;

    ID3DBlob* signature_blob = NULL;
    ID3DBlob* error_blob = NULL;

    hr = D3D12SerializeRootSignature(&root_sig_desc, D3D_ROOT_SIGNATURE_VERSION_1, &signature_blob,
                                     &error_blob);
    if (FAILED(hr))
    {
        if (error_blob)
        {
            fprintf(stderr, "D3D12: Root signature error: %s\n",
                    (char*)error_blob->lpVtbl->GetBufferPointer(error_blob));
            error_blob->lpVtbl->Release(error_blob);
        }
        return false;
    }

    hr = backend->device->lpVtbl->CreateRootSignature(
        backend->device, 0, signature_blob->lpVtbl->GetBufferPointer(signature_blob),
        signature_blob->lpVtbl->GetBufferSize(signature_blob), &IID_ID3D12RootSignature,
        (void**)&backend->root_signature);
    signature_blob->lpVtbl->Release(signature_blob);

    if (FAILED(hr))
    {
        fprintf(stderr, "D3D12: Failed to create root signature (hr=0x%08lX)\n", hr);
        return false;
    }

    /* Define vertex input layout */
    D3D12_INPUT_ELEMENT_DESC input_layout[] = {
        {"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0,
         D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0},
        {"COLOR", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, 12,
         D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0},
    };

    /* Create pipeline state object */
    D3D12_GRAPHICS_PIPELINE_STATE_DESC pso_desc = {0};
    pso_desc.pRootSignature = backend->root_signature;
    pso_desc.VS.pShaderBytecode = g_vs_bytecode;
    pso_desc.VS.BytecodeLength = sizeof(g_vs_bytecode);
    pso_desc.PS.pShaderBytecode = g_ps_bytecode;
    pso_desc.PS.BytecodeLength = sizeof(g_ps_bytecode);

    /* Blend state - no blending */
    pso_desc.BlendState.AlphaToCoverageEnable = FALSE;
    pso_desc.BlendState.IndependentBlendEnable = FALSE;
    pso_desc.BlendState.RenderTarget[0].BlendEnable = FALSE;
    pso_desc.BlendState.RenderTarget[0].LogicOpEnable = FALSE;
    pso_desc.BlendState.RenderTarget[0].RenderTargetWriteMask = D3D12_COLOR_WRITE_ENABLE_ALL;

    pso_desc.SampleMask = UINT_MAX;

    /* Rasterizer state */
    pso_desc.RasterizerState.FillMode = D3D12_FILL_MODE_SOLID;
    pso_desc.RasterizerState.CullMode = D3D12_CULL_MODE_NONE;
    pso_desc.RasterizerState.FrontCounterClockwise = FALSE;
    pso_desc.RasterizerState.DepthBias = 0;
    pso_desc.RasterizerState.DepthBiasClamp = 0.0f;
    pso_desc.RasterizerState.SlopeScaledDepthBias = 0.0f;
    pso_desc.RasterizerState.DepthClipEnable = TRUE;
    pso_desc.RasterizerState.MultisampleEnable = FALSE;
    pso_desc.RasterizerState.AntialiasedLineEnable = FALSE;
    pso_desc.RasterizerState.ForcedSampleCount = 0;
    pso_desc.RasterizerState.ConservativeRaster = D3D12_CONSERVATIVE_RASTERIZATION_MODE_OFF;

    /* Depth stencil state - enabled with depth test */
    pso_desc.DepthStencilState.DepthEnable = TRUE;
    pso_desc.DepthStencilState.DepthWriteMask = D3D12_DEPTH_WRITE_MASK_ALL;
    pso_desc.DepthStencilState.DepthFunc = D3D12_COMPARISON_FUNC_LESS;
    pso_desc.DepthStencilState.StencilEnable = FALSE;
    pso_desc.DSVFormat = DXGI_FORMAT_D32_FLOAT;

    pso_desc.InputLayout.pInputElementDescs = input_layout;
    pso_desc.InputLayout.NumElements = 2;
    pso_desc.PrimitiveTopologyType = D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;
    pso_desc.NumRenderTargets = 1;
    pso_desc.RTVFormats[0] = DXGI_FORMAT_R8G8B8A8_UNORM;
    pso_desc.SampleDesc.Count = 1;
    pso_desc.SampleDesc.Quality = 0;

    hr = backend->device->lpVtbl->CreateGraphicsPipelineState(
        backend->device, &pso_desc, &IID_ID3D12PipelineState, (void**)&backend->pipeline_state);
    if (FAILED(hr))
    {
        fprintf(stderr, "D3D12: Failed to create pipeline state (hr=0x%08lX)\n", hr);
        return false;
    }

    return true;
}

void d3d12_destroy_triangle_pipeline(D3D12Backend* backend)
{
    if (backend->pipeline_state)
    {
        backend->pipeline_state->lpVtbl->Release(backend->pipeline_state);
        backend->pipeline_state = NULL;
    }
    if (backend->root_signature)
    {
        backend->root_signature->lpVtbl->Release(backend->root_signature);
        backend->root_signature = NULL;
    }
}

/* =============================================================================
 * Vertex Buffer
 * ============================================================================= */

/* Vertex format: position (float3) + color (float4) = 28 bytes */
typedef struct D3D12Vertex
{
    float position[3];
    float color[4];
} D3D12Vertex;

b8 d3d12_create_triangle_buffers(D3D12Backend* backend)
{
    /* Triangle vertices (in clip space) */
    D3D12Vertex vertices[] = {
        {{0.0f, 0.5f, 0.0f}, {1.0f, 0.0f, 0.0f, 1.0f}},   /* Top - red */
        {{0.5f, -0.5f, 0.0f}, {0.0f, 1.0f, 0.0f, 1.0f}},  /* Bottom right - green */
        {{-0.5f, -0.5f, 0.0f}, {0.0f, 0.0f, 1.0f, 1.0f}}, /* Bottom left - blue */
    };

    u32 vertex_buffer_size = sizeof(vertices);

    /* Create upload heap vertex buffer */
    D3D12_HEAP_PROPERTIES heap_props = {0};
    heap_props.Type = D3D12_HEAP_TYPE_UPLOAD;
    heap_props.CPUPageProperty = D3D12_CPU_PAGE_PROPERTY_UNKNOWN;
    heap_props.MemoryPoolPreference = D3D12_MEMORY_POOL_UNKNOWN;
    heap_props.CreationNodeMask = 1;
    heap_props.VisibleNodeMask = 1;

    D3D12_RESOURCE_DESC resource_desc = {0};
    resource_desc.Dimension = D3D12_RESOURCE_DIMENSION_BUFFER;
    resource_desc.Alignment = 0;
    resource_desc.Width = vertex_buffer_size;
    resource_desc.Height = 1;
    resource_desc.DepthOrArraySize = 1;
    resource_desc.MipLevels = 1;
    resource_desc.Format = DXGI_FORMAT_UNKNOWN;
    resource_desc.SampleDesc.Count = 1;
    resource_desc.SampleDesc.Quality = 0;
    resource_desc.Layout = D3D12_TEXTURE_LAYOUT_ROW_MAJOR;
    resource_desc.Flags = D3D12_RESOURCE_FLAG_NONE;

    HRESULT hr = backend->device->lpVtbl->CreateCommittedResource(
        backend->device, &heap_props, D3D12_HEAP_FLAG_NONE, &resource_desc,
        D3D12_RESOURCE_STATE_GENERIC_READ, NULL, &IID_ID3D12Resource,
        (void**)&backend->vertex_buffer);
    if (FAILED(hr))
    {
        fprintf(stderr, "D3D12: Failed to create vertex buffer (hr=0x%08lX)\n", hr);
        return false;
    }

    /* Map and copy vertex data */
    void* mapped_data = NULL;
    D3D12_RANGE read_range = {0, 0}; /* We don't intend to read */
    hr = backend->vertex_buffer->lpVtbl->Map(backend->vertex_buffer, 0, &read_range, &mapped_data);
    if (FAILED(hr))
    {
        fprintf(stderr, "D3D12: Failed to map vertex buffer (hr=0x%08lX)\n", hr);
        return false;
    }

    memcpy(mapped_data, vertices, vertex_buffer_size);
    backend->vertex_buffer->lpVtbl->Unmap(backend->vertex_buffer, 0, NULL);

    /* Set up vertex buffer view */
    backend->vertex_buffer_view.BufferLocation =
        backend->vertex_buffer->lpVtbl->GetGPUVirtualAddress(backend->vertex_buffer);
    backend->vertex_buffer_view.SizeInBytes = vertex_buffer_size;
    backend->vertex_buffer_view.StrideInBytes = sizeof(D3D12Vertex);

    return true;
}

void d3d12_destroy_triangle_buffers(D3D12Backend* backend)
{
    if (backend->vertex_buffer)
    {
        backend->vertex_buffer->lpVtbl->Release(backend->vertex_buffer);
        backend->vertex_buffer = NULL;
    }
}

    /* =============================================================================
     * Constant Buffers
     * ============================================================================= */

    /* Constant buffer size must be 256-byte aligned */
    #define CB_ALIGN 256
    #define CB_SIZE ((sizeof(float) * 16 + CB_ALIGN - 1) & ~(CB_ALIGN - 1))

b8 d3d12_create_constant_buffers(D3D12Backend* backend)
{
    HRESULT hr;

    /* Create upload heap constant buffers (one per frame) */
    D3D12_HEAP_PROPERTIES heap_props = {0};
    heap_props.Type = D3D12_HEAP_TYPE_UPLOAD;
    heap_props.CPUPageProperty = D3D12_CPU_PAGE_PROPERTY_UNKNOWN;
    heap_props.MemoryPoolPreference = D3D12_MEMORY_POOL_UNKNOWN;
    heap_props.CreationNodeMask = 1;
    heap_props.VisibleNodeMask = 1;

    D3D12_RESOURCE_DESC resource_desc = {0};
    resource_desc.Dimension = D3D12_RESOURCE_DIMENSION_BUFFER;
    resource_desc.Alignment = 0;
    resource_desc.Width = CB_SIZE;
    resource_desc.Height = 1;
    resource_desc.DepthOrArraySize = 1;
    resource_desc.MipLevels = 1;
    resource_desc.Format = DXGI_FORMAT_UNKNOWN;
    resource_desc.SampleDesc.Count = 1;
    resource_desc.SampleDesc.Quality = 0;
    resource_desc.Layout = D3D12_TEXTURE_LAYOUT_ROW_MAJOR;
    resource_desc.Flags = D3D12_RESOURCE_FLAG_NONE;

    for (UINT i = 0; i < D3D12_FRAME_COUNT; i++)
    {
        hr = backend->device->lpVtbl->CreateCommittedResource(
            backend->device, &heap_props, D3D12_HEAP_FLAG_NONE, &resource_desc,
            D3D12_RESOURCE_STATE_GENERIC_READ, NULL, &IID_ID3D12Resource,
            (void**)&backend->constant_buffers[i]);
        if (FAILED(hr))
        {
            fprintf(stderr, "D3D12: Failed to create constant buffer %u (hr=0x%08lX)\n", i, hr);
            return false;
        }

        /* Keep constant buffers persistently mapped */
        D3D12_RANGE read_range = {0, 0};
        hr = backend->constant_buffers[i]->lpVtbl->Map(backend->constant_buffers[i], 0, &read_range,
                                                       &backend->constant_buffer_mapped[i]);
        if (FAILED(hr))
        {
            fprintf(stderr, "D3D12: Failed to map constant buffer %u (hr=0x%08lX)\n", i, hr);
            return false;
        }

        /* Initialize with identity matrix */
        float identity[16] = {1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1};
        memcpy(backend->constant_buffer_mapped[i], identity, sizeof(identity));
    }

    return true;
}

void d3d12_destroy_constant_buffers(D3D12Backend* backend)
{
    for (UINT i = 0; i < D3D12_FRAME_COUNT; i++)
    {
        if (backend->constant_buffers[i])
        {
            backend->constant_buffers[i]->lpVtbl->Unmap(backend->constant_buffers[i], 0, NULL);
            backend->constant_buffers[i]->lpVtbl->Release(backend->constant_buffers[i]);
            backend->constant_buffers[i] = NULL;
            backend->constant_buffer_mapped[i] = NULL;
        }
    }
}

void d3d12_set_transform(D3D12Backend* backend, const float* mvp)
{
    if (!backend->constant_buffer_mapped[backend->frame_index])
        return;

    memcpy(backend->constant_buffer_mapped[backend->frame_index], mvp, sizeof(float) * 16);
}

/* =============================================================================
 * Depth Buffer
 * ============================================================================= */

b8 d3d12_create_depth_buffer(D3D12Backend* backend)
{
    HRESULT hr;

    /* Create DSV descriptor heap */
    D3D12_DESCRIPTOR_HEAP_DESC dsv_heap_desc = {0};
    dsv_heap_desc.Type = D3D12_DESCRIPTOR_HEAP_TYPE_DSV;
    dsv_heap_desc.NumDescriptors = 1;
    dsv_heap_desc.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_NONE;
    dsv_heap_desc.NodeMask = 0;

    hr = backend->device->lpVtbl->CreateDescriptorHeap(
        backend->device, &dsv_heap_desc, &IID_ID3D12DescriptorHeap, (void**)&backend->dsv_heap);
    if (FAILED(hr))
    {
        fprintf(stderr, "D3D12: Failed to create DSV heap (hr=0x%08lX)\n", hr);
        return false;
    }

    /* Create depth buffer */
    D3D12_HEAP_PROPERTIES heap_props = {0};
    heap_props.Type = D3D12_HEAP_TYPE_DEFAULT;
    heap_props.CPUPageProperty = D3D12_CPU_PAGE_PROPERTY_UNKNOWN;
    heap_props.MemoryPoolPreference = D3D12_MEMORY_POOL_UNKNOWN;
    heap_props.CreationNodeMask = 1;
    heap_props.VisibleNodeMask = 1;

    D3D12_RESOURCE_DESC depth_desc = {0};
    depth_desc.Dimension = D3D12_RESOURCE_DIMENSION_TEXTURE2D;
    depth_desc.Alignment = 0;
    depth_desc.Width = backend->width;
    depth_desc.Height = backend->height;
    depth_desc.DepthOrArraySize = 1;
    depth_desc.MipLevels = 1;
    depth_desc.Format = DXGI_FORMAT_D32_FLOAT;
    depth_desc.SampleDesc.Count = 1;
    depth_desc.SampleDesc.Quality = 0;
    depth_desc.Layout = D3D12_TEXTURE_LAYOUT_UNKNOWN;
    depth_desc.Flags = D3D12_RESOURCE_FLAG_ALLOW_DEPTH_STENCIL;

    D3D12_CLEAR_VALUE clear_value = {0};
    clear_value.Format = DXGI_FORMAT_D32_FLOAT;
    clear_value.DepthStencil.Depth = 1.0f;
    clear_value.DepthStencil.Stencil = 0;

    hr = backend->device->lpVtbl->CreateCommittedResource(
        backend->device, &heap_props, D3D12_HEAP_FLAG_NONE, &depth_desc,
        D3D12_RESOURCE_STATE_DEPTH_WRITE, &clear_value, &IID_ID3D12Resource,
        (void**)&backend->depth_buffer);
    if (FAILED(hr))
    {
        fprintf(stderr, "D3D12: Failed to create depth buffer (hr=0x%08lX)\n", hr);
        return false;
    }

    /* Create DSV */
    D3D12_DEPTH_STENCIL_VIEW_DESC dsv_desc = {0};
    dsv_desc.Format = DXGI_FORMAT_D32_FLOAT;
    dsv_desc.ViewDimension = D3D12_DSV_DIMENSION_TEXTURE2D;
    dsv_desc.Flags = D3D12_DSV_FLAG_NONE;
    dsv_desc.Texture2D.MipSlice = 0;

    D3D12_CPU_DESCRIPTOR_HANDLE dsv_handle;
    backend->dsv_heap->lpVtbl->GetCPUDescriptorHandleForHeapStart(backend->dsv_heap, &dsv_handle);

    backend->device->lpVtbl->CreateDepthStencilView(backend->device, backend->depth_buffer,
                                                    &dsv_desc, dsv_handle);

    return true;
}

void d3d12_destroy_depth_buffer(D3D12Backend* backend)
{
    if (backend->depth_buffer)
    {
        backend->depth_buffer->lpVtbl->Release(backend->depth_buffer);
        backend->depth_buffer = NULL;
    }
    if (backend->dsv_heap)
    {
        backend->dsv_heap->lpVtbl->Release(backend->dsv_heap);
        backend->dsv_heap = NULL;
    }
}

/* =============================================================================
 * Triangle Drawing
 * ============================================================================= */

void d3d12_draw_triangle(D3D12Backend* backend)
{
    if (!backend->pipeline_state || !backend->vertex_buffer)
        return;

    /* Set pipeline state */
    backend->command_list->lpVtbl->SetPipelineState(backend->command_list, backend->pipeline_state);
    backend->command_list->lpVtbl->SetGraphicsRootSignature(backend->command_list,
                                                            backend->root_signature);

    /* Bind constant buffer (root CBV at slot 0) */
    D3D12_GPU_VIRTUAL_ADDRESS cb_address =
        backend->constant_buffers[backend->frame_index]->lpVtbl->GetGPUVirtualAddress(
            backend->constant_buffers[backend->frame_index]);
    backend->command_list->lpVtbl->SetGraphicsRootConstantBufferView(backend->command_list, 0,
                                                                     cb_address);

    /* Set vertex buffer */
    backend->command_list->lpVtbl->IASetVertexBuffers(backend->command_list, 0, 1,
                                                      &backend->vertex_buffer_view);
    backend->command_list->lpVtbl->IASetPrimitiveTopology(backend->command_list,
                                                          D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);

    /* Draw */
    backend->command_list->lpVtbl->DrawInstanced(backend->command_list, 3, 1, 0, 0);
}

/* =============================================================================
 * Mesh Operations
 * ============================================================================= */

b8 d3d12_upload_mesh(D3D12Backend* backend, const void* vertices, u32 vertex_count,
                     u32 vertex_stride, const u32* indices, u32 index_count)
{
    HRESULT hr;

    /* Clean up any existing mesh */
    d3d12_destroy_mesh(backend);

    if (!vertices || vertex_count == 0 || vertex_stride == 0)
        return false;

    /* Create vertex buffer */
    D3D12_HEAP_PROPERTIES heap_props = {0};
    heap_props.Type = D3D12_HEAP_TYPE_UPLOAD;
    heap_props.CPUPageProperty = D3D12_CPU_PAGE_PROPERTY_UNKNOWN;
    heap_props.MemoryPoolPreference = D3D12_MEMORY_POOL_UNKNOWN;
    heap_props.CreationNodeMask = 1;
    heap_props.VisibleNodeMask = 1;

    u32 vb_size = vertex_count * vertex_stride;
    D3D12_RESOURCE_DESC vb_desc = {0};
    vb_desc.Dimension = D3D12_RESOURCE_DIMENSION_BUFFER;
    vb_desc.Alignment = 0;
    vb_desc.Width = vb_size;
    vb_desc.Height = 1;
    vb_desc.DepthOrArraySize = 1;
    vb_desc.MipLevels = 1;
    vb_desc.Format = DXGI_FORMAT_UNKNOWN;
    vb_desc.SampleDesc.Count = 1;
    vb_desc.SampleDesc.Quality = 0;
    vb_desc.Layout = D3D12_TEXTURE_LAYOUT_ROW_MAJOR;
    vb_desc.Flags = D3D12_RESOURCE_FLAG_NONE;

    hr = backend->device->lpVtbl->CreateCommittedResource(
        backend->device, &heap_props, D3D12_HEAP_FLAG_NONE, &vb_desc,
        D3D12_RESOURCE_STATE_GENERIC_READ, NULL, &IID_ID3D12Resource,
        (void**)&backend->mesh_vertex_buffer);
    if (FAILED(hr))
    {
        fprintf(stderr, "D3D12: Failed to create mesh vertex buffer (hr=0x%08lX)\n", hr);
        return false;
    }

    /* Upload vertex data */
    void* mapped = NULL;
    D3D12_RANGE read_range = {0, 0};
    hr = backend->mesh_vertex_buffer->lpVtbl->Map(backend->mesh_vertex_buffer, 0, &read_range,
                                                  &mapped);
    if (FAILED(hr))
    {
        fprintf(stderr, "D3D12: Failed to map mesh vertex buffer\n");
        return false;
    }
    memcpy(mapped, vertices, vb_size);
    backend->mesh_vertex_buffer->lpVtbl->Unmap(backend->mesh_vertex_buffer, 0, NULL);

    /* Set up vertex buffer view */
    backend->mesh_vbv.BufferLocation =
        backend->mesh_vertex_buffer->lpVtbl->GetGPUVirtualAddress(backend->mesh_vertex_buffer);
    backend->mesh_vbv.SizeInBytes = vb_size;
    backend->mesh_vbv.StrideInBytes = vertex_stride;
    backend->mesh_vertex_count = vertex_count;

    /* Create index buffer if provided */
    if (indices && index_count > 0)
    {
        u32 ib_size = index_count * sizeof(u32);
        D3D12_RESOURCE_DESC ib_desc = vb_desc;
        ib_desc.Width = ib_size;

        hr = backend->device->lpVtbl->CreateCommittedResource(
            backend->device, &heap_props, D3D12_HEAP_FLAG_NONE, &ib_desc,
            D3D12_RESOURCE_STATE_GENERIC_READ, NULL, &IID_ID3D12Resource,
            (void**)&backend->mesh_index_buffer);
        if (FAILED(hr))
        {
            fprintf(stderr, "D3D12: Failed to create mesh index buffer (hr=0x%08lX)\n", hr);
            return false;
        }

        /* Upload index data */
        hr = backend->mesh_index_buffer->lpVtbl->Map(backend->mesh_index_buffer, 0, &read_range,
                                                     &mapped);
        if (FAILED(hr))
        {
            fprintf(stderr, "D3D12: Failed to map mesh index buffer\n");
            return false;
        }
        memcpy(mapped, indices, ib_size);
        backend->mesh_index_buffer->lpVtbl->Unmap(backend->mesh_index_buffer, 0, NULL);

        /* Set up index buffer view */
        backend->mesh_ibv.BufferLocation =
            backend->mesh_index_buffer->lpVtbl->GetGPUVirtualAddress(backend->mesh_index_buffer);
        backend->mesh_ibv.SizeInBytes = ib_size;
        backend->mesh_ibv.Format = DXGI_FORMAT_R32_UINT;
        backend->mesh_index_count = index_count;
    }

    return true;
}

void d3d12_destroy_mesh(D3D12Backend* backend)
{
    if (backend->mesh_index_buffer)
    {
        backend->mesh_index_buffer->lpVtbl->Release(backend->mesh_index_buffer);
        backend->mesh_index_buffer = NULL;
    }
    if (backend->mesh_vertex_buffer)
    {
        backend->mesh_vertex_buffer->lpVtbl->Release(backend->mesh_vertex_buffer);
        backend->mesh_vertex_buffer = NULL;
    }
    backend->mesh_vertex_count = 0;
    backend->mesh_index_count = 0;
}

void d3d12_draw_mesh(D3D12Backend* backend)
{
    if (!backend->pipeline_state || !backend->mesh_vertex_buffer)
        return;

    /* Set pipeline state */
    backend->command_list->lpVtbl->SetPipelineState(backend->command_list, backend->pipeline_state);
    backend->command_list->lpVtbl->SetGraphicsRootSignature(backend->command_list,
                                                            backend->root_signature);

    /* Bind constant buffer */
    D3D12_GPU_VIRTUAL_ADDRESS cb_address =
        backend->constant_buffers[backend->frame_index]->lpVtbl->GetGPUVirtualAddress(
            backend->constant_buffers[backend->frame_index]);
    backend->command_list->lpVtbl->SetGraphicsRootConstantBufferView(backend->command_list, 0,
                                                                     cb_address);

    /* Set vertex buffer */
    backend->command_list->lpVtbl->IASetVertexBuffers(backend->command_list, 0, 1,
                                                      &backend->mesh_vbv);
    backend->command_list->lpVtbl->IASetPrimitiveTopology(backend->command_list,
                                                          D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);

    /* Draw indexed or non-indexed */
    if (backend->mesh_index_buffer && backend->mesh_index_count > 0)
    {
        backend->command_list->lpVtbl->IASetIndexBuffer(backend->command_list, &backend->mesh_ibv);
        backend->command_list->lpVtbl->DrawIndexedInstanced(backend->command_list,
                                                            backend->mesh_index_count, 1, 0, 0, 0);
    }
    else
    {
        backend->command_list->lpVtbl->DrawInstanced(backend->command_list,
                                                     backend->mesh_vertex_count, 1, 0, 0);
    }
}

#endif /* BAV3D_PLATFORM_WINDOWS */
